<?xml version="1.0" encoding="utf-8"?>
<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove($(MSBuildThisFile), $(MSBuildThisFileDirectory)..))" />

  <PropertyGroup>
    <IsTestProject Condition="'$(MSBuildProjectExtension)' == '.csproj'">true</IsTestProject>
    <IsPackable>false</IsPackable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <PublishNativeAOTTests Condition="'$(MSBuildProjectExtension)' == '.csproj'">true</PublishNativeAOTTests>
  </PropertyGroup>

  <PropertyGroup Condition="'$(NativeAOT)' == 'true' and '$(PublishNativeAOTTests)' == 'true'">
    <RuntimeIdentifier>$(DefaultRuntimeIdentifier)</RuntimeIdentifier>
  </PropertyGroup>

</Project>
