<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Ubjson</RootNamespace>
    <EmitCompilerGeneratedFiles>false</EmitCompilerGeneratedFiles>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ShapeShift\ShapeShift.csproj" />
    <ProjectReference Include="..\..\src\ShapeShift.Conformance\ShapeShift.Conformance.csproj" />
  </ItemGroup>

</Project>
